# 1.0 Análise Inicial dos Dados

O dataset Cross-Sectional (transversal) funciona como uma fotografia instantânea, capturando informações de 436 indivíduos em um único momento no tempo, o que permite comparar as diferenças cerebrais entre pessoas de diversas idades e grupos demográficos. Já o dataset Longitudinal é focado no acompanhamento progressivo, registrando 373 exames de idosos que retornaram para múltiplas visitas ao longo dos anos. Enquanto o primeiro é mais amplo e serve para identificar padrões gerais da anatomia cerebral, o segundo é fundamental para observar a velocidade da atrofia e a evolução da doença no mesmo paciente, contendo variáveis específicas como o número da visita (Visit) e o tempo de intervalo entre os exames (MR Delay).

### 1.1 Importação das Bibliotecas Usadas

In [1]:
import pandas as pd
from sklearn.impute import KNNImputer

### 1.2 Importação dos Datasets

In [2]:
df_cross_sectional = pd.read_csv('Cross-Sectional.csv')
df_logintudinal = pd.read_csv('Logintudinal.csv')

pd.set_option('display.max_colwidth', None)

### 1.3 Descrição Dos Datasets

In [3]:
df_cross_sectional

,ID,M/F,Hand,Age,Educ,SES,MMSE,CDR,eTIV,nWBV,ASF,Delay
0,OAS1_0001_MR1,F,R,74,2.0,3.0,29.0,0.0,1344,0.743,1.306,NaN
1,OAS1_0002_MR1,F,R,55,4.0,1.0,29.0,0.0,1147,0.810,1.531,NaN
2,OAS1_0003_MR1,F,R,73,4.0,3.0,27.0,0.5,1454,0.708,1.207,NaN
3,OAS1_0004_MR1,M,R,28,NaN,NaN,NaN,NaN,1588,0.803,1.105,NaN
4,OAS1_0005_MR1,M,R,18,NaN,NaN,NaN,NaN,1737,0.848,1.010,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
431,OAS1_0285_MR2,M,R,20,NaN,NaN,NaN,NaN,1469,0.847,1.195,2.0
432,OAS1_0353_MR2,M,R,22,NaN,NaN,NaN,NaN,1684,0.790,1.042,40.0
433,OAS1_0368_MR2,M,R,22,NaN,NaN,NaN,NaN,1580,0.856,1.111,89.0
434,OAS1_0379_MR2,F,R,20,NaN,NaN,NaN,NaN,1262,0.861,1.390,2.0
435,OAS1_0395_MR2,F,R,26,NaN,NaN,NaN,NaN,1283,0.834,1.368,39.0

In [4]:
df_descricao_CrossSec = pd.read_csv('df_descricao_crossSec.csv')
df_descricao_CrossSec

,Nome da Coluna,Tipo de Dado,Descrição
0,ID / MRI ID,object,Identificador único do paciente ou do exame de ressonância.
1,M/F,object,Gênero do paciente (Masculino ou Feminino).
2,Hand,object,Mão dominante.
3,Age,int,Idade do paciente em anos no momento do exame.
4,Educ,float,Nível de escolaridade (anos de estudo).
5,SES,float,Status Socioeconômico (nível de renda/classe social).
6,MMSE,float,Pontuação no Mini-Exame do Estado Mental (avaliação cognitiva).
7,CDR,float,Clinical Dementia Rating (escala de gravidade da demência).
8,eTIV,int,Volume Intracraniano Total Estimado (mm³).
9,nWBV,float,Volume Cerebral Total Normalizado (proporção de massa cinzenta).
10,ASF,float,Atlas Scaling Factor (fator de escala para normalização).
11,Delay,float,Tempo de atraso entre as visitas ou exames de imagem.

In [5]:
df_logintudinal

,Subject ID,MRI ID,Group,Visit,MR Delay,M/F,Hand,Age,EDUC,SES,MMSE,CDR,eTIV,nWBV,ASF
0,OAS2_0001,OAS2_0001_MR1,Nondemented,1,0,M,R,87,14,2.0,27.0,0.0,1986.550000,0.696106,0.883440
1,OAS2_0001,OAS2_0001_MR2,Nondemented,2,457,M,R,88,14,2.0,30.0,0.0,2004.479526,0.681062,0.875539
2,OAS2_0002,OAS2_0002_MR1,Demented,1,0,M,R,75,12,NaN,23.0,0.5,1678.290000,0.736336,1.045710
3,OAS2_0002,OAS2_0002_MR2,Demented,2,560,M,R,76,12,NaN,28.0,0.5,1737.620000,0.713402,1.010000
4,OAS2_0002,OAS2_0002_MR3,Demented,3,1895,M,R,80,12,NaN,22.0,0.5,1697.911134,0.701236,1.033623
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
368,OAS2_0185,OAS2_0185_MR2,Demented,2,842,M,R,82,16,1.0,28.0,0.5,1692.880000,0.693926,1.036690
369,OAS2_0185,OAS2_0185_MR3,Demented,3,2297,M,R,86,16,1.0,26.0,0.5,1688.009649,0.675457,1.039686
370,OAS2_0186,OAS2_0186_MR1,Nondemented,1,0,F,R,61,13,2.0,30.0,0.0,1319.020000,0.801006,1.330540
371,OAS2_0186,OAS2_0186_MR2,Nondemented,2,763,F,R,63,13,2.0,30.0,0.0,1326.650000,0.795981,1.322890
372,OAS2_0186,OAS2_0186_MR3,Nondemented,3,1608,F,R,65,13,2.0,30.0,0.0,1332.944463,0.801248,1.316634

In [6]:
df_descricao_logintudinal = pd.read_csv('df_descricao_logintudinal.csv')
df_descricao_logintudinal

,Nome da Coluna,Tipo de Dado,Descrição
0,ID / Subject ID,object,Identificador único do paciente ou sujeito.
1,MRI ID,object,Identificador específico do exame de ressonância magnética.
2,Group,object,Classificação clínica: Demented (Com AD) ou Nondemented.
3,Visit,int,Número da visita (sequencial para dados longitudinais).
4,M/F,object,"Gênero do paciente (M: Masculino, F: Feminino)."
5,Hand,object,"Mão dominante (Geralmente todos são destros ""R"")."
6,Age,int,Idade do paciente no momento do exame.
7,Educ / EDUC,float,Anos de escolaridade concluídos.
8,SES,float,Status Socioeconômico (nível de renda/classe).
9,MMSE,float,Pontuação no Mini-Exame do Estado Mental (Teste cognitivo).
10,CDR,float,Clinical Dementia Rating (Gravidade da demência).
11,eTIV,int/float,Volume Intracraniano Total Estimado (em mm³).
12,nWBV,float,Volume Cerebral Total Normalizado (indicador de atrofia).
13,ASF,float,Atlas Scaling Factor (Fator de escala para normalização).
14,Delay / MR Delay,float,Tempo de atraso entre visitas ou exames de imagem.

### 1.4 Limpeza dos Dados

* Remoção de dados ausentes: Eliminar colunas que apresentem mais de 60% de valores faltantes (missing values).

* Limpeza de registros nulos: Remover todas as linhas onde a variável Group seja nula (NaN).

* Redução de dimensionalidade irrelevante: Descartar a coluna Hand, uma vez que ela possui apenas um valor único ("R") e não contribui para a diferenciação dos modelos.

* Codificação da variável alvo (Target): Criar uma nova coluna chamada Group, onde o valor 1 é atribuído a pacientes com Alzheimer (AD) e 0 para pacientes sem a doença.

* Imputação de dados: Criar uma instância do KNNImputer para preencher os valores faltantes restantes com base na similaridade dos vizinhos.

* Relatório de execução: Gerar e imprimir um relatório detalhando todas as alterações e imputações realizadas no dataset.

#### 1.4.1 Junção dos Datasets

In [7]:
df_cross_sectional = df_cross_sectional.rename(columns={'ID': 'MRI ID', 'Educ': 'EDUC'}) 

df_merged = pd.concat([df_cross_sectional, df_logintudinal], axis=0, ignore_index=True)
df_merged

,MRI ID,M/F,Hand,Age,EDUC,SES,MMSE,CDR,eTIV,nWBV,ASF,Delay,Subject ID,Group,Visit,MR Delay
0,OAS1_0001_MR1,F,R,74,2.0,3.0,29.0,0.0,1344.000000,0.743000,1.306000,NaN,NaN,NaN,NaN,NaN
1,OAS1_0002_MR1,F,R,55,4.0,1.0,29.0,0.0,1147.000000,0.810000,1.531000,NaN,NaN,NaN,NaN,NaN
2,OAS1_0003_MR1,F,R,73,4.0,3.0,27.0,0.5,1454.000000,0.708000,1.207000,NaN,NaN,NaN,NaN,NaN
3,OAS1_0004_MR1,M,R,28,NaN,NaN,NaN,NaN,1588.000000,0.803000,1.105000,NaN,NaN,NaN,NaN,NaN
4,OAS1_0005_MR1,M,R,18,NaN,NaN,NaN,NaN,1737.000000,0.848000,1.010000,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
804,OAS2_0185_MR2,M,R,82,16.0,1.0,28.0,0.5,1692.880000,0.693926,1.036690,NaN,OAS2_0185,Demented,2.0,842.0
805,OAS2_0185_MR3,M,R,86,16.0,1.0,26.0,0.5,1688.009649,0.675457,1.039686,NaN,OAS2_0185,Demented,3.0,2297.0
806,OAS2_0186_MR1,F,R,61,13.0,2.0,30.0,0.0,1319.020000,0.801006,1.330540,NaN,OAS2_0186,Nondemented,1.0,0.0
807,OAS2_0186_MR2,F,R,63,13.0,2.0,30.0,0.0,1326.650000,0.795981,1.322890,NaN,OAS2_0186,Nondemented,2.0,763.0
808,OAS2_0186_MR3,F,R,65,13.0,2.0,30.0,0.0,1332.944463,0.801248,1.316634,NaN,OAS2_0186,Nondemented,3.0,1608.0

#### 1.4.2 Remoção de Missing Values

In [8]:
def relatorio_valoresFaltantes(df):
    
    resumo_nulos = pd.DataFrame({
        'Coluna': df.columns,
        'Total de Nulos': df.isna().sum().values,
        'Porcentagem (%)': (df.isna().sum().values / len(df)) * 100
    })
    
    return resumo_nulos

def remover_coluna(df, colunas):
    
    df_filtrado = df.drop(columns=colunas)

    return df_filtrado

In [9]:
relatorio_dadosFaltantes = relatorio_valoresFaltantes(df_merged)
relatorio_dadosFaltantes

        Coluna  Total de Nulos  Porcentagem (%)
0       MRI ID               0         0.000000
1          M/F               0         0.000000
2         Hand               0         0.000000
3          Age               0         0.000000
4         EDUC             201        24.845488
5          SES             239        29.542645
6         MMSE             203        25.092707
7          CDR             201        24.845488
8         eTIV               0         0.000000
9         nWBV               0         0.000000
10         ASF               0         0.000000
11       Delay             789        97.527812
12  Subject ID             436        53.893696
13       Group             436        53.893696
14       Visit             436        53.893696
15    MR Delay             436        53.893696

In [10]:
limite = len(df_merged) * 0.4
df_merged = df_merged.dropna(thresh=limite, axis=1)

In [11]:
df_merged

,MRI ID,M/F,Hand,Age,EDUC,SES,MMSE,CDR,eTIV,nWBV,ASF,Subject ID,Group,Visit,MR Delay
0,OAS1_0001_MR1,F,R,74,2.0,3.0,29.0,0.0,1344.000000,0.743000,1.306000,NaN,NaN,NaN,NaN
1,OAS1_0002_MR1,F,R,55,4.0,1.0,29.0,0.0,1147.000000,0.810000,1.531000,NaN,NaN,NaN,NaN
2,OAS1_0003_MR1,F,R,73,4.0,3.0,27.0,0.5,1454.000000,0.708000,1.207000,NaN,NaN,NaN,NaN
3,OAS1_0004_MR1,M,R,28,NaN,NaN,NaN,NaN,1588.000000,0.803000,1.105000,NaN,NaN,NaN,NaN
4,OAS1_0005_MR1,M,R,18,NaN,NaN,NaN,NaN,1737.000000,0.848000,1.010000,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
804,OAS2_0185_MR2,M,R,82,16.0,1.0,28.0,0.5,1692.880000,0.693926,1.036690,OAS2_0185,Demented,2.0,842.0
805,OAS2_0185_MR3,M,R,86,16.0,1.0,26.0,0.5,1688.009649,0.675457,1.039686,OAS2_0185,Demented,3.0,2297.0
806,OAS2_0186_MR1,F,R,61,13.0,2.0,30.0,0.0,1319.020000,0.801006,1.330540,OAS2_0186,Nondemented,1.0,0.0
807,OAS2_0186_MR2,F,R,63,13.0,2.0,30.0,0.0,1326.650000,0.795981,1.322890,OAS2_0186,Nondemented,2.0,763.0
808,OAS2_0186_MR3,F,R,65,13.0,2.0,30.0,0.0,1332.944463,0.801248,1.316634,OAS2_0186,Nondemented,3.0,1608.0

#### 1.4.3  Remoção de todas as linhas onde a variável Group seja nula (NaN).

In [12]:
df_merged['Group'].isna().sum()

np.int64(436)

In [13]:
df_merged = df_merged.dropna(subset=['Group'])

In [14]:
df_merged['Group'].isna().sum()

np.int64(0)

#### 1.4.4 Redução de dimensionalidade irrelevante: Descartar a coluna Hand

In [15]:
df_merged = remover_coluna(df_merged, ['Hand'])

In [16]:
df_merged

,MRI ID,M/F,Age,EDUC,SES,MMSE,CDR,eTIV,nWBV,ASF,Subject ID,Group,Visit,MR Delay
436,OAS2_0001_MR1,M,87,14.0,2.0,27.0,0.0,1986.550000,0.696106,0.883440,OAS2_0001,Nondemented,1.0,0.0
437,OAS2_0001_MR2,M,88,14.0,2.0,30.0,0.0,2004.479526,0.681062,0.875539,OAS2_0001,Nondemented,2.0,457.0
438,OAS2_0002_MR1,M,75,12.0,NaN,23.0,0.5,1678.290000,0.736336,1.045710,OAS2_0002,Demented,1.0,0.0
439,OAS2_0002_MR2,M,76,12.0,NaN,28.0,0.5,1737.620000,0.713402,1.010000,OAS2_0002,Demented,2.0,560.0
440,OAS2_0002_MR3,M,80,12.0,NaN,22.0,0.5,1697.911134,0.701236,1.033623,OAS2_0002,Demented,3.0,1895.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
804,OAS2_0185_MR2,M,82,16.0,1.0,28.0,0.5,1692.880000,0.693926,1.036690,OAS2_0185,Demented,2.0,842.0
805,OAS2_0185_MR3,M,86,16.0,1.0,26.0,0.5,1688.009649,0.675457,1.039686,OAS2_0185,Demented,3.0,2297.0
806,OAS2_0186_MR1,F,61,13.0,2.0,30.0,0.0,1319.020000,0.801006,1.330540,OAS2_0186,Nondemented,1.0,0.0
807,OAS2_0186_MR2,F,63,13.0,2.0,30.0,0.0,1326.650000,0.795981,1.322890,OAS2_0186,Nondemented,2.0,763.0
808,OAS2_0186_MR3,F,65,13.0,2.0,30.0,0.0,1332.944463,0.801248,1.316634,OAS2_0186,Nondemented,3.0,1608.0

#### 1.4.5 Codificação da variável alvo (Target)

In [17]:
df_merged['Group'] = df_merged['Group'].apply(lambda x: 1 if x == 'Demented' else 0)

In [18]:
df_merged

,MRI ID,M/F,Age,EDUC,SES,MMSE,CDR,eTIV,nWBV,ASF,Subject ID,Group,Visit,MR Delay
436,OAS2_0001_MR1,M,87,14.0,2.0,27.0,0.0,1986.550000,0.696106,0.883440,OAS2_0001,0,1.0,0.0
437,OAS2_0001_MR2,M,88,14.0,2.0,30.0,0.0,2004.479526,0.681062,0.875539,OAS2_0001,0,2.0,457.0
438,OAS2_0002_MR1,M,75,12.0,NaN,23.0,0.5,1678.290000,0.736336,1.045710,OAS2_0002,1,1.0,0.0
439,OAS2_0002_MR2,M,76,12.0,NaN,28.0,0.5,1737.620000,0.713402,1.010000,OAS2_0002,1,2.0,560.0
440,OAS2_0002_MR3,M,80,12.0,NaN,22.0,0.5,1697.911134,0.701236,1.033623,OAS2_0002,1,3.0,1895.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
804,OAS2_0185_MR2,M,82,16.0,1.0,28.0,0.5,1692.880000,0.693926,1.036690,OAS2_0185,1,2.0,842.0
805,OAS2_0185_MR3,M,86,16.0,1.0,26.0,0.5,1688.009649,0.675457,1.039686,OAS2_0185,1,3.0,2297.0
806,OAS2_0186_MR1,F,61,13.0,2.0,30.0,0.0,1319.020000,0.801006,1.330540,OAS2_0186,0,1.0,0.0
807,OAS2_0186_MR2,F,63,13.0,2.0,30.0,0.0,1326.650000,0.795981,1.322890,OAS2_0186,0,2.0,763.0
808,OAS2_0186_MR3,F,65,13.0,2.0,30.0,0.0,1332.944463,0.801248,1.316634,OAS2_0186,0,3.0,1608.0

#### 1.4.6 Imputação de dados: Criar uma instância do KNNImputer para preencher os valores faltantes

In [19]:
colunas_tabela3 = ['Age', 'CDR', 'SES', 'nWBV', 'Visit', 'MMSE', 'ASF', 'eTIV', 'Group', 'MR Delay']
df_final = df_merged[colunas_tabela3]

imputer = KNNImputer(n_neighbors=5) 
df_imputed = pd.DataFrame(imputer.fit_transform(df_final), columns=df_final.columns)

In [23]:
df_imputed

,Age,CDR,SES,nWBV,Visit,MMSE,ASF,eTIV,Group,MR Delay
0,87.0,0.0,2.0,0.696106,1.0,27.0,0.883440,1986.550000,0.0,0.0
1,88.0,0.0,2.0,0.681062,2.0,30.0,0.875539,2004.479526,0.0,457.0
2,75.0,0.5,1.8,0.736336,1.0,23.0,1.045710,1678.290000,1.0,0.0
3,76.0,0.5,1.6,0.713402,2.0,28.0,1.010000,1737.620000,1.0,560.0
4,80.0,0.5,2.6,0.701236,3.0,22.0,1.033623,1697.911134,1.0,1895.0
...,...,...,...,...,...,...,...,...,...,...
368,82.0,0.5,1.0,0.693926,2.0,28.0,1.036690,1692.880000,1.0,842.0
369,86.0,0.5,1.0,0.675457,3.0,26.0,1.039686,1688.009649,1.0,2297.0
370,61.0,0.0,2.0,0.801006,1.0,30.0,1.330540,1319.020000,0.0,0.0
371,63.0,0.0,2.0,0.795981,2.0,30.0,1.322890,1326.650000,0.0,763.0
372,65.0,0.0,2.0,0.801248,3.0,30.0,1.316634,1332.944463,0.0,1608.0

In [24]:
df_imputed.to_csv("dataset_tratado.csv")

In [21]:
# data_crossSec = {
#     'Nome da Coluna': [
#         'ID / MRI ID', 'M/F', 'Hand', 'Age', 'Educ', 
#         'SES', 'MMSE', 'CDR', 'eTIV', 'nWBV', 
#         'ASF', 'Delay'
#     ],
#     'Tipo de Dado': [
#         'object', 'object', 'object', 'int', 'float', 
#         'float', 'float', 'float', 'int', 'float', 
#         'float','float'
#     ],
#     'Descrição': [
#         'Identificador único do paciente ou do exame de ressonância.',
#         'Gênero do paciente (Masculino ou Feminino).',
#         'Mão dominante.',
#         'Idade do paciente em anos no momento do exame.',
#         'Nível de escolaridade (anos de estudo).',
#         'Status Socioeconômico (nível de renda/classe social).',
#         'Pontuação no Mini-Exame do Estado Mental (avaliação cognitiva).',
#         'Clinical Dementia Rating (escala de gravidade da demência).',
#         'Volume Intracraniano Total Estimado (mm³).',
#         'Volume Cerebral Total Normalizado (proporção de massa cinzenta).',
#         'Atlas Scaling Factor (fator de escala para normalização).',
#         'Tempo de atraso entre as visitas ou exames de imagem.'
#     ]
# }

# df_descricao_CrossSec = pd.DataFrame(data_crossSec)
# df_descricao_CrossSec.to_csv('df_descricao_crossSec.csv', index=False, encoding='utf-8-sig')

In [22]:
#data_oasis = {
#     'Nome da Coluna': [
#         'ID / Subject ID', 'MRI ID', 'Group', 'Visit', 'M/F', 
#         'Hand', 'Age', 'Educ / EDUC', 'SES', 'MMSE', 
#         'CDR', 'eTIV', 'nWBV', 'ASF', 'Delay / MR Delay'
#     ],
#     'Tipo de Dado': [
#         'object', 'object', 'object', 'int', 'object', 
#         'object', 'int', 'float', 'float', 'float', 
#         'float', 'int/float', 'float', 'float', 'float'
#     ],
#     'Descrição': [
#         'Identificador único do paciente ou sujeito.',
#         'Identificador específico do exame de ressonância magnética.',
#         'Classificação clínica: Demented (Com AD) ou Nondemented.',
#         'Número da visita (sequencial para dados longitudinais).',
#         'Gênero do paciente (M: Masculino, F: Feminino).',
#         'Mão dominante (Geralmente todos são destros "R").',
#         'Idade do paciente no momento do exame.',
#         'Anos de escolaridade concluídos.',
#         'Status Socioeconômico (nível de renda/classe).',
#         'Pontuação no Mini-Exame do Estado Mental (Teste cognitivo).',
#         'Clinical Dementia Rating (Gravidade da demência).',
#         'Volume Intracraniano Total Estimado (em mm³).',
#         'Volume Cerebral Total Normalizado (indicador de atrofia).',
#         'Atlas Scaling Factor (Fator de escala para normalização).',
#         'Tempo de atraso entre visitas ou exames de imagem.'
#     ]
# }


# df_descricao_logintudinal = pd.DataFrame(data_oasis)
# df_descricao_logintudinal.to_csv('df_descricao_logintudinal.csv', index=False, encoding='utf-8-sig')